server:
  port: 8080

spring:
  devtools:
    restart:
      enabled: true
    restart.additional-exclude: static/**, public/**
  application:
    name: minha-api
  datasource:
    url: jdbc:h2:mem:testdb   # URL do H2 Database em memória
    driver-class-name: org.h2.Driver
    username: sa              # Usuário padrão do H2 Database
    password:                 # Senha padrão do H2 Database
  h2:
    console:
      enabled: true           # Ativar o console web do H2 Database
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
