server:
  port: 8080

spring:
  devtools:
    restart:
      enabled: true
    restart.additional-exclude: static/**, public/**
  application:
    name: minha-api
  datasource:
    url: jdbc:oracle:thin:@192.168.100.4:1521/FREEPDB1
    username: system
    password: S3gur@P@ssw0rd
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
