server:
  port: 8080

spring:
  devtools:
    restart:
      enabled: true
    restart.additional-exclude: static/**, public/**
  application:
    name: minha-api
  datasource:
    url: ${SPRING_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
